15 tk 016create page to enter sms otp
ADORSYS-GIS/webank-UserApp pull request #25
Opened 2024-10-21 14:40 UTC by NkwaTambe

### Title: Create SMS OTP Entry Page
Documentation Impl : https://dominicarrojado.com/posts/how-to-create-your-own-otp-input-in-react-and-typescript-with-tests-part-1/

Documentation Test : https://dominicarrojado.com/posts/how-to-create-your-own-otp-input-in-react-and-typescript-with-tests-part-2/

### Description:
This pull request introduces a new page for users to enter their SMS-based One-Time Password (OTP) during the authentication process. The implementation includes:

An intuitive layout with input fields for a 4-digit OTP.
Automatic focus management between input fields for enhanced user experience.
Validation to ensure only numeric input is accepted.
A resend OTP feature for user convenience.

2024-10-22 07:23 UTC, Arielpetit commented on index.html
>      <title>webank-UserApp + TS</title>
Hello @NkwaTambe Please change this title to Webank-UserApp

2024-10-22 07:23 UTC, Arielpetit reviewed
I think a test is missing, Please do well to add it

2024-10-23 06:54 UTC, Arielpetit approved these changes

2024-10-23 07:28 UTC, Arielpetit requested changes

2024-10-23 07:28 UTC, Arielpetit commented on src/components/OtpInput.tsx
> +  }, [value, valueLength]);
Please put that in a proper method with a method name and a unit test for that

2024-10-23 13:43 UTC, NkwaTambe commented on src/components/OtpInput.tsx
> +  }, [value, valueLength]);
done

2024-10-24 07:25 UTC, merged