chore: setup basic react pwa
ADORSYS-GIS/webank-UserApp pull request #4
Opened 2024-09-23 07:07 UTC by Koufan-De-King

Here I set up a basic react app using **Vite** initializer and made it a pwa using **Vite's PWA plugin** 
Find the procedure [here](https://vite-pwa-org.netlify.app/guide/).

Since we're using react and typescript, use the following to create your project
```npm create @vite-pwa/pwa@latest my-vue-app -- --template vue``` 
and then follow the steps to install and configure the plugin.

2024-09-23 07:53 UTC, NkwaTambe requested changes
@Koufan-De-King   it looks like the current push includes a lot of the default styling and configurations from the Vite React app setup that we won't need in this project. Could you please clean up the basic files **(like default CSS, icons, boilerplate components, etc.)** so that we can focus on our custom setup? We want to avoid unnecessary dependencies and keep the repository lightweight.

2024-09-23 13:38 UTC, Elwizzy12 approved these changes

2024-09-23 14:30 UTC, Arielpetit requested changes

2024-09-23 14:30 UTC, Arielpetit commented on README.md
> +- Install [eslint-plugin-react](https://github.com/jsx-eslint/eslint-plugin-react) and add `plugin:react/recommended` & `plugin:react/jsx-runtime` to the `extends` list
Hello @Koufan-De-King I don't think this is needed in the readme file, please try to review it again

2024-09-23 14:50 UTC, nancymuyeh approved these changes

2024-09-24 06:55 UTC, Arielpetit approved these changes

2024-09-24 07:08 UTC, NkwaTambe approved these changes

2024-09-24 07:20 UTC, merged