feat: generated key pairs on installation
ADORSYS-GIS/webank-UserApp pull request #41
Opened 2024-10-29 17:37 UTC by Arielpetit

generated key pairs on installation

2024-10-29 17:42 UTC, NkwaTambe requested changes

2024-10-29 17:42 UTC, NkwaTambe commented on src/App.tsx
> +
These should not be in App.tsx

2024-10-29 17:42 UTC, NkwaTambe commented on src/App.tsx
> +      <div className="app">
Why  here ???

2024-10-29 17:47 UTC, NkwaTambe reviewed
Can you implement a test for your components...

2024-10-31 07:06 UTC, francis-pouatcha approved these changes

2024-10-31 07:18 UTC, francis-pouatcha requested changes

2024-10-31 07:18 UTC, francis-pouatcha commented on src/services/keyManagement/generateKey.ts
> +  // Generate an RSA key pair
This is not an RSA key pair but an ec keypair

2024-10-31 07:18 UTC, francis-pouatcha commented on src/services/keyManagement/generateKey.ts
> +  console.log("Public Key:", publicJWK);
Please do not log keys. Write tests to validate generated keys.

2024-10-31 07:18 UTC, francis-pouatcha commented on src/services/keyManagement/generateKey.ts
> +  console.log("Private Key:", privateJWK);
Never log a private keys

2024-10-31 13:32 UTC, NkwaTambe commented
Please fix the failing test

2024-10-31 13:44 UTC, NkwaTambe requested changes

2024-10-31 13:44 UTC, NkwaTambe commented on jest.config.js
> +    testEnvironment: 'node',
The test environtment has been specified already in the `vitest.config.ts`....
we are using `jsdom` as our test environtment

2024-10-31 13:44 UTC, NkwaTambe commented on package.json
> -    "@types/jest": "^29.5.14",
we need these `types`..

`@types/jest` provides us we functions like `expect` which we use in our test

2024-10-31 13:44 UTC, NkwaTambe commented on src/pages/RegisterPage.tsx
>      }
Please where are you using these type in your code ??
i mean the type `CountryOption`

2024-10-31 13:44 UTC, NkwaTambe commented on src/pages/RegisterPage.tsx
> +      console.log("Generating key pair...");
please remove the `console.log`

2024-10-31 14:13 UTC, Arielpetit commented on src/pages/RegisterPage.tsx
>      }
line 18
line 19
line 26
line 30

2024-11-01 16:19 UTC, Elwizzy12 submitted a review, later dismissed

2024-11-01 16:19 UTC, Koufan-De-King approved these changes

2024-11-01 16:41 UTC, Koufan-De-King commented
This ticket was resolved in 
- [ ] #42

2024-11-01 16:42 UTC, closed without merging