Docker runtime
ADORSYS-GIS/webank-UserApp pull request #64
Opened 2024-11-25 09:27 UTC by Koufan-De-King

2024-11-25 10:20 UTC, stephane-segning commented on .env.example
> +VITE_FRONTEND_URL="https://mynameisnot
Why do you need the frontend url?

2024-11-25 10:23 UTC, Koufan-De-King commented on .env.example
> +VITE_FRONTEND_URL="https://mynameisnot
Oops, forgot it while testing for multiple variables. Will remove it!

2024-11-25 11:56 UTC, stephane-segning requested changes

2024-11-25 11:56 UTC, stephane-segning commented on src/shared/projectEnvVariables.ts
> +  VITE_OTHER_ENV_VARIABLE: "${VITE_OTHER_ENV_VARIABLE}",
What is this `OTHER_ENV_VARIABLE`?

2024-11-25 11:56 UTC, stephane-segning commented on src/shared/projectEnvVariables.ts
> +          : import.meta.env.VITE_OTHER_ENV_VARIABLE,
`OTHER_ENV_VARIABLE` is not use, isn't it? Please remove it.

2024-11-25 11:58 UTC, Koufan-De-King commented on src/shared/projectEnvVariables.ts
> +          : import.meta.env.VITE_OTHER_ENV_VARIABLE,
Okay. I will.

2024-11-25 14:20 UTC, stephane-segning submitted a review, later dismissed

2024-11-27 11:31 UTC, NkwaTambe approved these changes

2024-11-27 11:37 UTC, merged